### ISSUE TITLE
Presupuesto Inicial

### ISSUE THREAD

**Issue by micardona96** [imenesesl/social_control#10]
En el campo **Presupuesto Inicial**, en algunas ocasiones aparece un texto concatenado con una cifra de dinero, pareciera ser una fallo al convertir el csv.

pasos para analizar el caso, en _autocompletador_  buscar la comuna 19, seleccionar **FORTALECIMIENTO DE LA SEGURIDAD Y CONVIVENCIA CIUDADANA DE LA COMUNA 19 DE SANTIAGO DE CALI**, que es la ultima y se vera de forma correcta, a mi parecer,

![image](https://user-images.githubusercontent.com/37484798/56847827-7ea34580-68a6-11e9-8896-06e858357339.png)

**Ahora el caso con fallo, notado en el 90% de los datos, la mayoría de campos presentar los datos de esta forma, hacer la prueba con cualquier otro elemento de la comuna 19**

![image](https://user-images.githubusercontent.com/37484798/56847895-7a2b5c80-68a7-11e9-9327-4137e06b63cb.png)

**Comment by imenesesl** [comment]
@micardona96 es correcto lo que dices, eso se reportó con anterioridad en el issues que está aún vigente, el cual reporta que subir el archivo csv a la base de datos rompe algunos datos, se está trabajando actualmente en una forma correcta de subir dicho documento.
