### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by imenesesl** [imenesesl/social_control#21]
Se cambio el guion medio "-" por guion bajo "_" en todas las columnas de la base de dato, ese cambio se debe realizar para que todo funcione correctamente.

Consulte la API
https://github.com/imenesesl/social_control_service

**Comment by micardona96** [comment]
OMG

**Comment by micardona96** [comment]
![WhatsApp Image 2019-06-10 at 2 31 21 PM](https://user-images.githubusercontent.com/37484798/59226956-cef60e80-8b99-11e9-9bd7-b3198bdbfe48.jpeg)

Fix

**Comment by imenesesl** [comment]
gracias por tu observación, ya se realizaron los cambios pertinentes! Gracias
